import mongoose, { Schema, Document } from "mongoose";

export interface IProductMedia {
  id: string; // Keep as string for front-end compat, generated by backend
  type: "image" | "video";
  url: string;
  sortOrder: number;
  isPrimary: boolean;
}

export interface IProduct extends Document {
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  description: string;
  price: number;
  originalPrice?: number;
  salePrice?: number;
  stock: number;
  lowStockThreshold: number;
  status: "published" | "draft" | "archived" | "hidden";
  flags: {
    bestSeller: boolean;
    newArrival: boolean;
    featured: boolean;
    onSale: boolean;
    outOfStock: boolean;
  };
  media: IProductMedia[];
  image?: string;
  images?: string[];
  video?: string;
  benefits?: string | string[];
  ingredients?: string;
  howToUse?: string;
  characteristic?: string;
  suitableFor?: string;
  warnings?: string;
  size?: string;
  shades?: string[];
  variants?: string[];
  createdAt: Date;
  updatedAt: Date;
}

const ProductMediaSchema = new Schema(
  {
    id: { type: String, required: true },
    type: { type: String, enum: ["image", "video"], required: true },
    url: { type: String, required: true },
    sortOrder: { type: Number, required: true },
    isPrimary: { type: Boolean, default: false },
  },
  { _id: false } // We are using 'id' as a string instead of ObjectId for subdocs
);

const ProductSchema = new Schema(
  {
    name: { type: String, required: true },
    brand: { type: String, required: true },
    category: { type: String, required: true },
    subcategory: { type: String, default: "" },
    description: { type: String, default: "" },
    price: { type: Number, required: true, min: 0 },
    originalPrice: { type: Number },
    salePrice: { type: Number },
    stock: { type: Number, required: true, min: 0 },
    lowStockThreshold: { type: Number, default: 0 },
    status: { type: String, enum: ["published", "draft", "archived", "hidden"], default: "draft" },
    flags: {
      bestSeller: { type: Boolean, default: false },
      newArrival: { type: Boolean, default: false },
      featured: { type: Boolean, default: false },
      onSale: { type: Boolean, default: false },
      outOfStock: { type: Boolean, default: false },
    },
    media: [ProductMediaSchema],
    image: { type: String }, // Legacy
    images: [{ type: String }], // Legacy
    video: { type: String }, // Legacy
    benefits: { type: Schema.Types.Mixed }, // Can be string or string[]
    ingredients: { type: String },
    howToUse: { type: String },
    characteristic: { type: String },
    suitableFor: { type: String },
    warnings: { type: String },
    size: { type: String },
    shades: [{ type: String }],
    variants: [{ type: String }],
  },
  { timestamps: true }
);

export const Product = mongoose.model<IProduct>("Product", ProductSchema);
